### ISSUE TITLE
WebStorm not showing colors

### ISSUE THREAD

**Issue by Unthrottled** [one-dark/jetbrains-one-dark-theme#161]
Webstorm `Build #WS-201.7846.79, built on June 2, 2020` doesn't have the Groovy Util bundled, so the plugin cannot create themes on the fly (the EAP has it though).

```
java.lang.NoClassDefFoundError: groovy/util/XmlParser
	at com.markskelton.ThemeConstructor.getEditorXMLTemplate(ThemeConstructor.kt:220)
	at com.markskelton.ThemeConstructor.buildNewEditorScheme(ThemeConstructor.kt:100)
	at com.markskelton.ThemeConstructor.getUpdatedEditorScheme(ThemeConstructor.kt:86)
	at com.markskelton.ThemeConstructor.access$getUpdatedEditorScheme(ThemeConstructor.kt:48)
	at com.markskelton.ThemeConstructor$getPreExistingTheme$1.get(ThemeConstructor.kt:63)
	at com.markskelton.ThemeConstructor$getPreExistingTheme$1.get(ThemeConstructor.kt:48)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.markskelton.ThemeConstructor.getPreExistingTheme(ThemeConstructor.kt:62)
	at com.markskelton.ThemeConstructor.useExistingTheme(ThemeConstructor.kt:57)
	at com.markskelton.OneDarkThemeManager.setOneDarkTheme(OneDarkThemeManager.kt:99)
	at com.markskelton.OneDarkThemeManager.applyConfigurableTheme(OneDarkThemeManager.kt:93)
	at com.markskelton.OneDarkThemeManager.registerStartup(OneDarkThemeManager.kt:31)
	at com.markskelton.OneDarkTheme.runActivity(OneDarkTheme.kt:18)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:289)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:223)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:285)
....
```

**Comment by Narven** [comment]
One of the most beatiful themes and one I've been using for ages.... and yet after every single update, it fails to update the UI, and I have to go and change to some other theme and back... sereval times. I think that the next time this theme works... all future updates will be blocked.

It's really hard to understand how its possible to 😡 every single update. Either on linux or mac.

**Comment by Narven** [comment]
I dont undertand java... but please let me know if there is anything I can do.

**Comment by Unthrottled** [comment]
@Narven Hey! So you've got a couple option until the fix goes out.

You can:
- Update your WebStorm to the 2020.2 EAP (which fixes the issue)
- Manually install v3.3.6 [following these instructions](https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual) (replacing the latest release with the v3.3.6 version)

Thank You for your patience :smiley:

**Comment by Narven** [comment]
@Unthrottled thanks for the feedback

I really dont understand why the latest version only works in a EAP version. Shouldnt it work first on a stable version? or is not possible to bound the plugin version to a specific webstorm version?
I only work with stable versions of software (my work depends on it), I'm not going on a EAP just because of a plugin.

And for people that use multiple jetbrains IDE's like me and I use the same theme across all (I'm hopping that issue does not happen on all)

I will take a look and try the second approach. Thanks.

**Comment by Unthrottled** [comment]
Alright, fixes are live and I verified that the issue has been fixed.

**Comment by Narven** [comment]
Yeap, after update and restart, it seams to be working. Thanks

**Comment by Unthrottled** [comment]
@Narven 

> I really dont understand why the latest version only works in a EAP version.

Ah, so what the issue was is that I used a library that was only provided by the EAP version of the Idea platform. So when you installed it on the older Idea platform, the plugin could not use the library (because it was not there yet). So I just bundled it with plugin and that way the plugin always has it.
