### ISSUE TITLE
v4.0.1 fails to install properly, throws startup errors

### ISSUE THREAD

**Issue by PrasadU** [one-dark/jetbrains-one-dark-theme#168]
**After the latest v4.0.1 update IDEA. failed to start with below error msg **

```
The IDE failed to install some plugins.

Most probably, this happened because of a change in a serialization format.
Please try again, and if the problem persists, please report it
to http://jb.gg/ide/critical-startup-errors
```

**To Reproduce - Update**
Start with IDEA v2020.1 with one dark theme v4.0.0 
Go to the plugins panel, the plugin update alert comes for v4.0.1 - then update

**Expected Behavior**
normal plugin update

**Actual**
IDEA popped-up a msg that the entire plugin was removed.

**To Reproduce - Install**
Install the v4.0.1 

**Expected Behavior**
normal plugin install and activation 

**Actual**
IDEA fails to start

**Environment**
IntelliJ IDEA 2020.1.2 Ultimate Edition
Build #IU 201.7846.76
MacOS 10.15.5
plugin v4.0.1

**Other observation**
**Screenshots**
<img width="955" alt="oneDark - err" src="https://user-images.githubusercontent.com/5512901/86210319-4e22ff80-bb6c-11ea-90f4-57326f06f6ee.png">

<img width="391" alt="idea-about" src="https://user-images.githubusercontent.com/5512901/86210651-dd301780-bb6c-11ea-9245-4ccee5ec2568.png">

2020-07-01 07:13:11,959 [71621588]   INFO - lij.ide.plugins.DynamicPlugins - Plugin com.markskelton.one-dark-theme is not unload-safe because class loader cannot be unloaded 
java.net.MalformedURLException: Malformed URL: 
	at com.intellij.util.Urls.newFromEncoded(Urls.kt:63)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:101)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:86)
	at com.intellij.ide.plugins.PluginManagerConfigurable.loadRepositoryPlugins(PluginManagerConfigurable.java:1549)
2020-07-01 07:14:14,160 [71683789]   INFO -                         STDERR - ERROR: null 
2020-07-01 07:14:14,160 [71683789]   INFO -                         STDERR - Enclosed Exception: 
2020-07-01 07:14:14,160 [71683789]   INFO -                         STDERR - property.syntax.error.at [<unknown>, stroke-dasharray, null, invalid.identifier [stroke-dasharray, null]] 
2020-07-01 07:14:14,160 [71683789]   INFO -                         STDERR - org.w3c.dom.DOMException: property.syntax.error.at [<unknown>, stroke-width, null, invalid.lexical.unit [stroke-width, 35]] 
2020-07-01 07:14:14,160 [71683789]   INFO -                         STDERR - 	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:775)

**Comment by Unthrottled** [comment]
Very curious, I think this may be isolated to your machine. 
Here is what I have:

```
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on May 31, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, bigger.font.in.project.view=true, ide.open.readme.md.on.startup=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Key Promoter X, String Manipulation, com.github.novotnyr.jwt-intellij-plugin, Lombook Plugin, intellij.haskell, com.markskelton.one-dark-theme, io.acari.normandy.progress.bar, io.unthrottled.DokiTheme, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc
````

I am able to restart the IDE, and it starts up just fine.

I even ran `rm -rf ~/Library/Caches/JetBrains/IntelliJIdea2020.1/plugins/` and it still started fine. I even cleared the entire cache directory `rm -rf ~/Library/Caches/JetBrains/IntelliJIdea2020.1/` and it still started.

Could you try clearing out the intellij cache? Maybe when you downloaded the update, something happened and your download got corrupted.

**Comment by Unthrottled** [comment]
If that does not work.

[Could you follow these instructions and install v4.0.1 manually, please?](https://one-dark.gitbook.io/jetbrains/the-basics/installation#manual). Let me know what that does for you.

Thank you!

**Comment by PrasadU** [comment]
A second attempt (via plugins panel) worked. So it may be just be an intermittent n/w error in download. You can close the this issue if it was just me. Thanks.

**Comment by Unthrottled** [comment]
I am glad re-installing the plugin worked for you! I have not observed any other related errors that might have been related to this. I'll say that this is a one-off issue for the time being.

Thanks for taking the time to submit this issue!
